### ISSUE TITLE
dashboard.json should be optional, instead breaks

### ISSUE THREAD

**Issue by birm** [sharmalab/Datascope#17]
Error: ENOENT: no such file or directory, open 'config/dashboard.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at exports.getDashboardConfig (/Users/birm/Desktop/git/Datascope/routes/rest.js:44:16)
    at Layer.handle [as handle_request] (/Users/birm/Desktop/git/Datascope/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/birm/Desktop/git/Datascope/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/birm/Desktop/git/Datascope/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/birm/Desktop/git/Datascope/node_modules/express/lib/router/layer.js:95:5)
    at /Users/birm/Desktop/git/Datascope/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/birm/Desktop/git/Datascope/node_modules/express/lib/router/index.js:335:12)

**Comment by birm** [comment]
solved with 5356e3e
